.TH  "thunar\-settings" "1" "2015\-09\-19"
.SH "NAME" 
thunar\-settings \- display thunar(1) preferences dialog
.SH "SYNOPSIS" 
.PP 
.B thunar\-settings 
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the \fBthunar\-settings\fR command. 
.PP 
.B thunar\-settings 
shows the \fBthunar\fR(1) preferences dialog, and accept no options. 
.SH "SEE ALSO" 
.BR  thunar "(1)" 
.SH "AUTHORS" 
.PP
thunar\-settings is copyright \(co 2004\-2007 The Thunar development team. All
rights reserved.
.PP
This manual page was written by Francois Wendling <frwendling@posteo.net> for the
Debian GNU/Linux system (but may be used by others). 
