/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static inline void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_thunar_thumbnail_cache_proxy
#define DBUS_GLIB_CLIENT_WRAPPERS_thunar_thumbnail_cache_proxy

static inline gboolean
thunar_thumbnail_cache_proxy_move (DBusGProxy *proxy, const char ** IN_from_uris, const char ** IN_to_uris, GError **error)

{
  return dbus_g_proxy_call (proxy, "Move", error, G_TYPE_STRV, IN_from_uris, G_TYPE_STRV, IN_to_uris, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*thunar_thumbnail_cache_proxy_move_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
thunar_thumbnail_cache_proxy_move_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(thunar_thumbnail_cache_proxy_move_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static inline DBusGProxyCall*
thunar_thumbnail_cache_proxy_move_async (DBusGProxy *proxy, const char ** IN_from_uris, const char ** IN_to_uris, thunar_thumbnail_cache_proxy_move_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "Move", thunar_thumbnail_cache_proxy_move_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_STRV, IN_from_uris, G_TYPE_STRV, IN_to_uris, G_TYPE_INVALID);
}
static inline gboolean
thunar_thumbnail_cache_proxy_copy (DBusGProxy *proxy, const char ** IN_from_uris, const char ** IN_to_uris, GError **error)

{
  return dbus_g_proxy_call (proxy, "Copy", error, G_TYPE_STRV, IN_from_uris, G_TYPE_STRV, IN_to_uris, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*thunar_thumbnail_cache_proxy_copy_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
thunar_thumbnail_cache_proxy_copy_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(thunar_thumbnail_cache_proxy_copy_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static inline DBusGProxyCall*
thunar_thumbnail_cache_proxy_copy_async (DBusGProxy *proxy, const char ** IN_from_uris, const char ** IN_to_uris, thunar_thumbnail_cache_proxy_copy_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "Copy", thunar_thumbnail_cache_proxy_copy_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_STRV, IN_from_uris, G_TYPE_STRV, IN_to_uris, G_TYPE_INVALID);
}
static inline gboolean
thunar_thumbnail_cache_proxy_delete (DBusGProxy *proxy, const char ** IN_uris, GError **error)

{
  return dbus_g_proxy_call (proxy, "Delete", error, G_TYPE_STRV, IN_uris, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*thunar_thumbnail_cache_proxy_delete_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
thunar_thumbnail_cache_proxy_delete_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(thunar_thumbnail_cache_proxy_delete_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static inline DBusGProxyCall*
thunar_thumbnail_cache_proxy_delete_async (DBusGProxy *proxy, const char ** IN_uris, thunar_thumbnail_cache_proxy_delete_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "Delete", thunar_thumbnail_cache_proxy_delete_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_STRV, IN_uris, G_TYPE_INVALID);
}
static inline gboolean
thunar_thumbnail_cache_proxy_cleanup (DBusGProxy *proxy, const char ** IN_base_uris, const guint IN_since, GError **error)

{
  return dbus_g_proxy_call (proxy, "Cleanup", error, G_TYPE_STRV, IN_base_uris, G_TYPE_UINT, IN_since, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*thunar_thumbnail_cache_proxy_cleanup_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
thunar_thumbnail_cache_proxy_cleanup_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(thunar_thumbnail_cache_proxy_cleanup_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static inline DBusGProxyCall*
thunar_thumbnail_cache_proxy_cleanup_async (DBusGProxy *proxy, const char ** IN_base_uris, const guint IN_since, thunar_thumbnail_cache_proxy_cleanup_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "Cleanup", thunar_thumbnail_cache_proxy_cleanup_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_STRV, IN_base_uris, G_TYPE_UINT, IN_since, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_thunar_thumbnail_cache_proxy */

G_END_DECLS
